package com.yourcompany.kmptemplate.core.ui.theme

import androidx.compose.ui.graphics.Color

// Generated from Material Theme Builder — seed #6750A4 (M3 baseline purple).
// Replace with your brand seed at https://material-foundation.github.io/material-theme-builder/
internal val primaryLight = Color(0xFF6650A4)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFEADDFF)
internal val onPrimaryContainerLight = Color(0xFF4F378B)
internal val secondaryLight = Color(0xFF625B71)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFE8DEF8)
internal val onSecondaryContainerLight = Color(0xFF4A4458)
internal val tertiaryLight = Color(0xFF7D5260)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFFFD8E4)
internal val onTertiaryContainerLight = Color(0xFF633B48)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFFEF7FF)
internal val onBackgroundLight = Color(0xFF1D1B20)
internal val surfaceLight = Color(0xFFFEF7FF)
internal val onSurfaceLight = Color(0xFF1D1B20)
internal val surfaceVariantLight = Color(0xFFE7E0EC)
internal val onSurfaceVariantLight = Color(0xFF49454F)
internal val outlineLight = Color(0xFF79747E)
internal val outlineVariantLight = Color(0xFFCAC4D0)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF322F35)
internal val inverseOnSurfaceLight = Color(0xFFF5EFF7)
internal val inversePrimaryLight = Color(0xFFD0BCFF)
internal val surfaceDimLight = Color(0xFFDED8E1)
internal val surfaceBrightLight = Color(0xFFFEF7FF)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF7F2FA)
internal val surfaceContainerLight = Color(0xFFF3EDF7)
internal val surfaceContainerHighLight = Color(0xFFECE6F0)
internal val surfaceContainerHighestLight = Color(0xFFE6E0E9)

internal val primaryDark = Color(0xFFD0BCFF)
internal val onPrimaryDark = Color(0xFF381E72)
internal val primaryContainerDark = Color(0xFF4F378B)
internal val onPrimaryContainerDark = Color(0xFFEADDFF)
internal val secondaryDark = Color(0xFFCCC2DC)
internal val onSecondaryDark = Color(0xFF332D41)
internal val secondaryContainerDark = Color(0xFF4A4458)
internal val onSecondaryContainerDark = Color(0xFFE8DEF8)
internal val tertiaryDark = Color(0xFFEFB8C8)
internal val onTertiaryDark = Color(0xFF492532)
internal val tertiaryContainerDark = Color(0xFF633B48)
internal val onTertiaryContainerDark = Color(0xFFFFD8E4)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF141218)
internal val onBackgroundDark = Color(0xFFE6E0E9)
internal val surfaceDark = Color(0xFF141218)
internal val onSurfaceDark = Color(0xFFE6E0E9)
internal val surfaceVariantDark = Color(0xFF49454F)
internal val onSurfaceVariantDark = Color(0xFFCAC4D0)
internal val outlineDark = Color(0xFF938F99)
internal val outlineVariantDark = Color(0xFF49454F)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFE6E0E9)
internal val inverseOnSurfaceDark = Color(0xFF322F35)
internal val inversePrimaryDark = Color(0xFF6650A4)
internal val surfaceDimDark = Color(0xFF141218)
internal val surfaceBrightDark = Color(0xFF3B383E)
internal val surfaceContainerLowestDark = Color(0xFF0F0D13)
internal val surfaceContainerLowDark = Color(0xFF1D1B20)
internal val surfaceContainerDark = Color(0xFF211F26)
internal val surfaceContainerHighDark = Color(0xFF2B2930)
internal val surfaceContainerHighestDark = Color(0xFF36343B)
